spring:
    datasource:
        driver-class-name: org.h2.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testDB
        username: sa
        password:
        hikari:
            pool-name: "H2Pool"
            minimum-idle: 1
            maximum-pool-size: 5
            connection-timeout: 10000
            validation-timeout: 5000
            idle-timeout: 600000
    h2:
        console:
            enabled: true
            path: /h2-console

    sql:
        init:
            encoding: utf-8
server:
    port: 10053


mybatis:
    mapper-locations: classpath:mappers/*.xml
